name: 'dbt_development'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
#this is just a custom list of directories where docs blocks are located. 
docs-paths: ["docs"]

#to use dbt project evaluator, need to run: dbt build --select package:dbt_project_evaluator
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_project_evaluator', 'spark_utils', 'dbt_utils']

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
models:
  dbt_development:
    # Applies to all files under models/jaffleshop/
    jaffle_shop:
      +materialized: view
      +incremental_strategy: merge
      +post-hook:
      - '{{ grant_privileges(this) }}'
      staging:
        +tags: staging_models
#arbitrarily dropping stg_payments model from my db on run start to make sure i understand the functionality
on-run-start: drop table if exists hive_metastore.dbt_flierheimer.stg_payments_final
on-run-end:
- '{% if target.name == ''prod'' %}{{ grant_default_schema_permissions(schemas) }}{% else %}{{ grant_default_schema_permissions(schemas, keep_owner=True) }}{%
  endif %}'
      
