version: 2
sources:
  - name: default
    tables:
      - name: jaffle_shop_customers
        tags: ['jaffle']
        columns:
          - name: id
          - name: first_name
          - name: last_name
      - name: jaffle_shop_orders
        loaded_at_field: order_date
        tags: ['jaffle']
        freshness:
          warn_after:
            count: 900
            period: day
          error_after:
            count: 2000
            period: day
        columns:
          - name: id
          - name: user_id
          - name: order_date
          - name: status

      - name: stripe_payments
        columns:
          - name: id
          - name: orderid
          - name: paymentmethod
          - name: status
          - name: amount
          - name: created
      - name: dbt_pnormile_usda_commodity_volume_report
        columns:
          - name: commodity
          - name: mode
          - name: origin
          - name: range_type
          - name: start_Time
          - name: end_time
          - name: units
          - name: units_value
          - name: value
          - name: file_date
          - name: link_name
          - name: time 
      - name: hubspot_names
        columns:
          - name: hubspot_id
          - name: hubspot_name
          - name: hubspot_website
          - name: company_id