version: 2
sources:
  - name: default
    tables:
      - name: jaffle_shop_customers
        columns:
          - name: id
          - name: first_name
          - name: last_name

      - name: jaffle_shop_orders
        columns:
          - name: id
          - name: user_id
          - name: order_date
          - name: status

      - name: stripe_payments
        columns:
          - name: id
          - name: orderid
          - name: paymentmethod
          - name: status
          - name: amount
          - name: created